parameters:
#    api_snippet.example.class: Api\SnippetBundle\Example

services:
#    api_snippet.example:
#        class: %api_snippet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
