<?php

namespace App\SnippetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SnippetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnippetRepository extends EntityRepository
{
	const TYPE_TEXT = 1;
    const TYPE_IMG = 2;
    const TYPE_CSS = 3;
	const TYPE_JS = 4;
	const TYPE_CSS_LINK = 5;
	const TYPE_JS_LINK = 6;

    public static function getTypeName($type){
        switch ($type){
            case self::TYPE_TEXT:
                return 'Text/HTML';
            case self::TYPE_IMG:
                return 'Image';
            case self::TYPE_CSS:
                return 'CSS';
            case self::TYPE_JS:
                return 'Javascript';
            case self::TYPE_CSS_LINK:
            	return 'CSS File';
            case self::TYPE_JS_LINK:
            	return 'Javascript File';
        }
    }
	
	public function findByAccount_id($accountId){

		$repository = $this->getDoctrine()
    		->getRepository('AppSnippetBundle:Snippet');

		$query = $repository->createQueryBuilder('s')
		    ->where('s.is_deleted = ?', false)
		    ->addWhere('s.account_id = ?', $accountId)
		    ->orderBy('s.name', 'ASC')
		    ->getQuery();

		$snippets = $query->getResult();
	}
	
	public function getArchivedSnippets(){
		
	}
}
