<?php

namespace App\SnippetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SnippetAuditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnippetAuditRepository extends EntityRepository
{
	const SYNC_STATUS_ERROR = 0;
	const SYNC_STATUS_NEW = 1;
	const SYNC_STATUS_PROCESSING = 2;
	const SYNC_STATUS_SYNCED = 3;
	const SYNC_STATUS_SKIPPED = 4;
}