# app/config/security.yml
security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    firewalls:
        styles: #Allow anonymous access to javascript & css files
            pattern:    ^/(favicon.ico|web|bootstrap|css|js)
            security:   false
        api_firewall:
            pattern:    ^/api
            anonymous:  ~
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
        secured_area:
            pattern:    ^/
            form_login: 
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

    #providers:
    #    in_memory:
    #        memory:
    #            users:
    #                eric:  { password: ericpass, roles: 'ROLE_USER' }
    #                admin: { password: kitten, roles: 'ROLE_ADMIN' }

    providers:
        main:
            entity: { class: App\UserBundle\Entity\User, property: email }

    encoders:
        App\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
