parameters:
#    app_home.example.class: App\HomeBundle\Example

services:
#    app_home.example:
#        class: %app_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
